-- AlterTable
ALTER TABLE "ETIQUETAS" ADD COLUMN     "CENTRO_ENTREGA" TEXT,
ADD COLUMN     "CENTRO_FATURAMENTO" TEXT,
ADD COLUMN     "COD_BARRA" TEXT,
ADD COLUMN     "COD_BARRA_CD_ATUAL" TEXT,
ADD COLUMN     "COD_DCO" TEXT,
ADD COLUMN     "DES_AUXILIAR_1" TEXT,
ADD COLUMN     "DES_AUXILIAR_2" TEXT,
ADD COLUMN     "DES_CODIGO_DESTINO" TEXT,
ADD COLUMN     "DES_ENDERECO" TEXT,
ADD COLUMN     "QTD_TOTAL" TEXT,
ADD COLUMN     "QUANTIDADE_PECA" TEXT;
