-- CreateTable
CREATE TABLE "ETIQUETAS_DINAMICAS" (
    "id" TEXT NOT NULL,
    "NOME" TEXT NOT NULL,
    "EMPRESA_ID" INTEGER NOT NULL,
    "TEMPLATE" TEXT NOT NULL,
    "COMPLETE_OPTIONS" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ETIQUETAS_DINAMICAS_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "ETIQUETAS_DINAMICAS" ADD CONSTRAINT "ETIQUETAS_DINAMICAS_EMPRESA_ID_fkey" FOREIGN KEY ("EMPRESA_ID") REFERENCES "Empresa"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
