import { Template } from '@pdfme/common'

export class CeADynamicInsoleTemplate {
    private template: Template

    constructor() {
        this.template = {
            schemas: [
                [
                    {
                        name: 'MODELO1',
                        type: 'multiVariableText',
                        content: "{'MODELO1':'MODELO1'}",
                        position: { x: 0, y: 4 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{MODELO1}',
                        variables: ['MODELO1'],
                        required: false,
                    },
                    {
                        name: 'MODELO2',
                        type: 'multiVariableText',
                        content: "{'MODELO2':'MODELO2'}",
                        position: { x: 0, y: 39 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{MODELO2}',
                        variables: ['MODELO2'],
                        required: false,
                    },
                    {
                        name: 'MODELO3',
                        type: 'multiVariableText',
                        content: "{'MODELO3':'MODELO3'}",
                        position: { x: 0, y: 74 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{MODELO3}',
                        variables: ['MODELO3'],
                        required: false,
                    },
                    {
                        name: 'CNPJ1',
                        type: 'multiVariableText',
                        content: "{'CNPJ1':'CNPJ1'}",
                        position: { x: 0, y: 9 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 7,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{CNPJ1}',
                        variables: ['CNPJ1'],
                        required: false,
                    },
                    {
                        name: 'CNPJ2',
                        type: 'multiVariableText',
                        content: "{'CNPJ2':'CNPJ2'}",
                        position: { x: 0, y: 44 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 7,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{CNPJ2}',
                        variables: ['CNPJ2'],
                        required: false,
                    },
                    {
                        name: 'CNPJ3',
                        type: 'multiVariableText',
                        content: "{'CNPJ3':'CNPJ3'}",
                        position: { x: 0, y: 79 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 7,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{CNPJ3}',
                        variables: ['CNPJ3'],
                        required: false,
                    },
                    {
                        name: 'CAB1',
                        type: 'multiVariableText',
                        content: "{'CAB1':'CAB1'}",
                        position: { x: 0, y: 13 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 6,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{CAB1}',
                        variables: ['CAB1'],
                        required: false,
                    },
                    {
                        name: 'CAB2',
                        type: 'multiVariableText',
                        content: "{'CAB2':'CAB2'}",
                        position: { x: 0, y: 48 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 6,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{CAB2}',
                        variables: ['CAB2'],
                        required: false,
                    },
                    {
                        name: 'CAB3',
                        type: 'multiVariableText',
                        content: "{'CAB3':'CAB3'}",
                        position: { x: 0, y: 83 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 6,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{CAB3}',
                        variables: ['CAB3'],
                        required: false,
                    },
                    {
                        name: 'FORRO1',
                        type: 'multiVariableText',
                        content: "{'FORRO1':'FORRO1'}",
                        position: { x: 0, y: 17 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 6,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{FORRO1}',
                        variables: ['FORRO1'],
                        required: false,
                    },
                    {
                        name: 'FORRO2',
                        type: 'multiVariableText',
                        content: "{'FORRO2':'FORRO2'}",
                        position: { x: 0, y: 51.5 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 6,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{FORRO2}',
                        variables: ['FORRO2'],
                        required: false,
                    },
                    {
                        name: 'FORRO3',
                        type: 'multiVariableText',
                        content: "{'FORRO3':'FORRO3'}",
                        position: { x: 0, y: 86.5 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 6,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{FORRO3}',
                        variables: ['FORRO3'],
                        required: false,
                    },
                    {
                        name: 'SOLA1',
                        type: 'multiVariableText',
                        content: "{'SOLA1':'SOLA1'}",
                        position: { x: 0, y: 21 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 6,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{SOLA1}',
                        variables: ['SOLA1'],
                        required: false,
                    },
                    {
                        name: 'SOLA2',
                        type: 'multiVariableText',
                        content: "{'SOLA2':'SOLA2'}",
                        position: { x: 0, y: 55 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 6,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{SOLA2}',
                        variables: ['SOLA2'],
                        required: false,
                    },
                    {
                        name: 'SOLA3',
                        type: 'multiVariableText',
                        content: "{'SOLA3':'SOLA3'}",
                        position: { x: 0, y: 90 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 6,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{SOLA3}',
                        variables: ['SOLA3'],
                        required: false,
                    },
                    {
                        name: 'FAB1',
                        type: 'text',
                        content: 'FAB1',
                        position: { x: 0, y: 24 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 6,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'FAB2',
                        type: 'text',
                        content: 'FAB2',
                        position: { x: 0, y: 58 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 6,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'FAB3',
                        type: 'text',
                        content: 'FAB3',
                        position: { x: 0, y: 93 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 6,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'COD1',
                        type: 'multiVariableText',
                        content: "{'COD1':'COD1'}",
                        position: { x: 0, y: 27 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{COD1}',
                        variables: ['COD1'],
                        required: false,
                    },
                    {
                        name: 'COD2',
                        type: 'multiVariableText',
                        content: "{'COD2':'COD2'}",
                        position: { x: 0, y: 61 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{COD2}',
                        variables: ['COD2'],
                        required: false,
                    },
                    {
                        name: 'COD3',
                        type: 'multiVariableText',
                        content: "{'COD3':'COD3'}",
                        position: { x: 0, y: 96 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{COD3}',
                        variables: ['COD3'],
                        required: false,
                    },
                    {
                        name: 'FORN1',
                        type: 'multiVariableText',
                        content: "{'FORN1':'FORN1'}",
                        position: { x: 0, y: 30 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{FORN1}',
                        variables: ['FORN1'],
                        required: false,
                    },
                    {
                        name: 'FORN2',
                        type: 'multiVariableText',
                        content: "{'FORN2':'FORN2'}",
                        position: { x: 0, y: 64 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{FORN2}',
                        variables: ['FORN2'],
                        required: false,
                    },
                    {
                        name: 'FORN3',
                        type: 'multiVariableText',
                        content: "{'FORN3':'FORN3'}",
                        position: { x: 0, y: 99 },
                        width: 28,
                        height: 2.5,
                        rotate: 0,
                        alignment: 'center',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Helvetica_Condensed_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{FORN3}',
                        variables: ['FORN3'],
                        required: false,
                    },
                ],
            ],
            basePdf:
                'data:application/pdf;base64,JVBERi0xLjQKMSAwIG9iago8PAovVHlwZSAvQ2F0YWxvZwovUGFnZXMgMiAwIFIKPj4KZW5kb2JqCjIgMCBvYmoKPDwKL1R5cGUgL1BhZ2VzCi9Db3VudCAxCi9LaWRzIFszIDAgUl0KPj4KZW5kb2JqCjMgMCBvYmoKPDwKL1R5cGUgL1BhZ2UKL1BhcmVudCAyIDAgUgovTWVkaWFCb3ggWzAgMCA4Mi4yMDQgMjk3LjYzOF0KL0NvbnRlbnRzIDQgMCBSCi9SZXNvdXJjZXMgPDwgPj4KPj4KZW5kb2JqCjQgMCBvYmoKPDwKL0xlbmd0aCA5Cj4+CnN0cmVhbQplbmRzdHJlYW0KZW5kb2JqCnhyZWYKMCA1CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAxMCAwMDAwMCBuIAowMDAwMDAwMDYwIDAwMDAwIG4gCjAwMDAwMDAxMTQgMDAwMDAgbiAKMDAwMDAwMDI2NyAwMDAwMCBuIAp0cmFpbGVyCjw8Ci9TaXplIDUKL1Jvb3QgMSAwIFIKPj4Kc3RhcnR4cmVmCjI4OAolJUVPRg==',
            pdfmeVersion: '5.5.6',
        }
    }

    public getTemplate(): Template {
        return this.template
    }
}
