import { Template } from '@pdfme/common'

export class CeAPackTemplate {
    private template: Template

    constructor() {
        this.template = {
            schemas: [
                [
                    {
                        name: 'RECTAGULE1',
                        type: 'rectangle',
                        position: { x: 4, y: 3 },
                        width: 42,
                        height: 4,
                        rotate: 0,
                        opacity: 1,
                        borderWidth: 0.2,
                        borderColor: '#000000',
                        color: '',
                        readOnly: true,
                        radius: 0,
                        required: false,
                        content: '',
                    },
                    {
                        name: 'PACK',
                        type: 'text',
                        content: 'PACK',
                        position: { x: 34.93, y: 3.4 },
                        width: 9.52,
                        height: 3.44,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'middle',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'VCR',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'CMS2',
                        type: 'multiVariableText',
                        content: '{"CMS2":"CMS2"}',
                        position: { x: 9, y: 8 },
                        width: 7,
                        height: 3,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'VCR',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{CMS2}',
                        variables: ['CMS2'],
                        required: false,
                    },
                    {
                        name: 'N_PEDIDO',
                        type: 'multiVariableText',
                        content: '{"N_PEDIDO":"N_PEDIDO"}',
                        position: { x: 14, y: 8 },
                        width: 15.08,
                        height: 3,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'VCR',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{N_PEDIDO}',
                        variables: ['N_PEDIDO'],
                        required: false,
                    },
                    {
                        name: 'IT',
                        type: 'multiVariableText',
                        content: '{"IT":"IT"}',
                        position: { x: 27, y: 8 },
                        width: 6,
                        height: 3,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'VCR',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{IT}',
                        variables: ['IT'],
                        required: false,
                    },
                    {
                        name: 'DA1',
                        type: 'multiVariableText',
                        content: '{"DA1":"DA1"}',
                        position: { x: 32, y: 8 },
                        width: 8,
                        height: 3,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'VCR',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{DA1}',
                        variables: ['DA1'],
                        required: false,
                    },
                    {
                        name: 'DA2',
                        type: 'multiVariableText',
                        content: '{"DA2":"DA2"}',
                        position: { x: 38, y: 8 },
                        width: 8,
                        height: 3,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'VCR',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{DA2}',
                        variables: ['DA2'],
                        required: false,
                    },
                    {
                        name: 'CODBAR',
                        type: 'code93',
                        content: '12345678901234',
                        position: { x: 2, y: 11.5 },
                        backgroundColor: '#ffffff',
                        barColor: '#000000',
                        textColor: '#000000',
                        includetext: false,
                        width: 48,
                        height: 8,
                        rotate: 0,
                        opacity: 0.7,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'SUB',
                        type: 'multiVariableText',
                        content: '{"SUB":"SUB"}',
                        position: { x: 7.5, y: 20 },
                        width: 15,
                        height: 3.44,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'VCR',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{SUB}',
                        variables: ['SUB'],
                        required: false,
                    },
                    {
                        name: 'CMS',
                        type: 'multiVariableText',
                        content: '{"CMS":"CMS"}',
                        position: { x: 28, y: 20 },
                        width: 25,
                        height: 3,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 5.5,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'MM_Condensed_L',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{CMS}',
                        variables: ['CMS'],
                        required: false,
                    },
                    {
                        name: 'PACK1',
                        type: 'text',
                        content: 'PACK1',
                        position: { x: 3.21, y: 24 },
                        width: 10,
                        height: 3.97,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 6,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'VCR',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'IT2',
                        type: 'multiVariableText',
                        content: '{"IT2":"IT2"}',
                        position: { x: 22.5, y: 24 },
                        width: 5.56,
                        height: 3.97,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 6,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'VCR',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{IT2}',
                        variables: ['IT2'],
                        required: false,
                    },
                    {
                        name: 'GR1',
                        type: 'multiVariableText',
                        content: '{"GR1":"GR1"}',
                        position: { x: 24, y: 24 },
                        width: 20,
                        height: 4.23,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 6,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'VCR',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{GR1}',
                        variables: ['GR1'],
                        required: false,
                    },
                ],
            ],
            basePdf:
                'data:application/pdf;base64,JVBERi0xLjQKMSAwIG9iago8PAovVHlwZSAvQ2F0YWxvZwovUGFnZXMgMiAwIFIKPj4KZW5kb2JqCjIgMCBvYmoKPDwKL1R5cGUgL1BhZ2VzCi9Db3VudCAxCi9LaWRzIFszIDAgUl0KPj4KZW5kb2JqCjMgMCBvYmoKPDwKL1R5cGUgL1BhZ2UKL1BhcmVudCAyIDAgUgovTWVkaWFCb3ggWzAgMCAxNDcuNDAyIDczLjcwMV0KL0NvbnRlbnRzIDQgMCBSCi9SZXNvdXJjZXMgPDwgPj4KPj4KZW5kb2JqCjQgMCBvYmoKPDwKL0xlbmd0aCA5Cj4+CnN0cmVhbQplbmRzdHJlYW0KZW5kb2JqCnhyZWYKMCA1CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAxMCAwMDAwMCBuIAowMDAwMDAwMDYwIDAwMDAwIG4gCjAwMDAwMDAxMTQgMDAwMDAgbiAKMDAwMDAwMDI2NyAwMDAwMCBuIAp0cmFpbGVyCjw8Ci9TaXplIDUKL1Jvb3QgMSAwIFIKPj4Kc3RhcnR4cmVmCjI4OAolJUVPRg==',
        }
    }

    public getTemplate(): Template {
        return this.template
    }
}
