import { Template } from '@pdfme/common'

export class PernambucanasTagTemplate {
    private template: Template

    constructor() {
        this.template = {
            schemas: [
                [
                    {
                        name: 'CodBar1',
                        type: 'code128',
                        content: 'This is Code 128!',
                        position: { x: 3, y: 12 },
                        backgroundColor: '#ffffff',
                        barColor: '#000000',
                        textColor: '#000000',
                        includetext: false,
                        width: 38,
                        height: 7,
                        rotate: 0,
                        opacity: 0.8,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'CodBar2',
                        type: 'code128',
                        content: 'This is Code 128!',
                        position: { x: 52, y: 12 },
                        backgroundColor: '#ffffff',
                        barColor: '#000000',
                        textColor: '#000000',
                        includetext: false,
                        width: 38,
                        height: 7,
                        rotate: 0,
                        opacity: 0.8,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'img1',
                        type: 'image',
                        content: 'TEST',
                        position: { x: 1.7, y: 2.7 },
                        width: 18,
                        height: 4.5,
                        rotate: 0,
                        opacity: 1,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'img2',
                        type: 'image',
                        content: 'TEST',
                        position: { x: 50.7, y: 2.7 },
                        width: 18,
                        height: 4.5,
                        rotate: 0,
                        opacity: 1,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'Pedido1',
                        type: 'text',
                        content: 'Pedido',
                        position: { x: 20, y: 3 },
                        width: 8,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 5.8,
                        lineHeight: 1,
                        characterSpacing: 0.4,
                        fontColor: '#000000',
                        fontName: 'swiss_Black',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'Pedido2',
                        type: 'text',
                        content: 'Pedido',
                        position: { x: 69, y: 3 },
                        width: 8,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 5.8,
                        lineHeight: 1,
                        characterSpacing: 0.4,
                        fontColor: '#000000',
                        fontName: 'swiss_Black',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'Artigo1',
                        type: 'text',
                        content: 'Artigo',
                        position: { x: 20, y: 5.5 },
                        width: 8,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 5.8,
                        lineHeight: 1,
                        characterSpacing: 0.4,
                        fontColor: '#000000',
                        fontName: 'swiss_Black',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'Artigo2',
                        type: 'text',
                        content: 'Artigo',
                        position: { x: 69, y: 5.5 },
                        width: 8,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 5.8,
                        lineHeight: 1,
                        characterSpacing: 0.4,
                        fontColor: '#000000',
                        fontName: 'swiss_Black',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'N_PEDIDO1',
                        type: 'multiVariableText',
                        content: '{"N_PEDIDO1":"N_PEDIDO1"}',
                        position: { x: 27.5, y: 3 },
                        width: 20,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 5.8,
                        lineHeight: 1,
                        characterSpacing: 0.4,
                        fontColor: '#000000',
                        fontName: 'swiss_Black',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{N_PEDIDO1}',
                        variables: ['N_PEDIDO1'],
                        required: false,
                    },
                    {
                        name: 'N_PEDIDO2',
                        type: 'multiVariableText',
                        content: '{"N_PEDIDO2":"N_PEDIDO2"}',
                        position: { x: 76.5, y: 3 },
                        width: 20,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 5.8,
                        lineHeight: 1,
                        characterSpacing: 0.4,
                        fontColor: '#000000',
                        fontName: 'swiss_Black',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{N_PEDIDO2}',
                        variables: ['N_PEDIDO2'],
                        required: false,
                    },
                    {
                        name: 'ARTIGO1',
                        type: 'multiVariableText',
                        content: '{"ARTIGO1":"ARTIGO1"}',
                        position: { x: 26.5, y: 5.5 },
                        width: 20,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 5.8,
                        lineHeight: 1,
                        characterSpacing: 0.4,
                        fontColor: '#000000',
                        fontName: 'swiss_Black',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{ARTIGO1}',
                        variables: ['ARTIGO1'],
                        required: false,
                    },
                    {
                        name: 'ARTIGO2',
                        type: 'multiVariableText',
                        content: '{"ARTIGO2":"ARTIGO2"}',
                        position: { x: 75.5, y: 5.5 },
                        width: 20,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 5.8,
                        lineHeight: 1,
                        characterSpacing: 0.4,
                        fontColor: '#000000',
                        fontName: 'swiss_Black',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{ARTIGO2}',
                        variables: ['ARTIGO2'],
                        required: false,
                    },
                    {
                        name: 'DESCRICAO1',
                        type: 'multiVariableText',
                        content: '{"DESCRICAO1":"DESCRICAO1"}',
                        position: { x: 2.8, y: 8.5 },
                        width: 38,
                        height: 3,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 5.8,
                        lineHeight: 1,
                        characterSpacing: 0.4,
                        fontColor: '#000000',
                        fontName: 'swiss_Black',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{DESCRICAO1}',
                        variables: ['DESCRICAO1'],
                        required: false,
                    },
                    {
                        name: 'DESCRICAO2',
                        type: 'multiVariableText',
                        content: '{"DESCRICAO2":"DESCRICAO2"}',
                        position: { x: 51.8, y: 8.5 },
                        width: 38,
                        height: 3,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 5.8,
                        lineHeight: 1,
                        characterSpacing: 0.4,
                        fontColor: '#000000',
                        fontName: 'swiss_Black',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{DESCRICAO2}',
                        variables: ['DESCRICAO2'],
                        required: false,
                    },
                ],
            ],
            basePdf:
                'data:application/pdf;base64,JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUl0gL0NvdW50IDEgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCAyNjkuMjkxIDU2LjY5M10gL0NvbnRlbnRzIDQgMCBSIC9SZXNvdXJjZXMgPDwgPj4gPj4KZW5kb2JqCjQgMCBvYmoKPDwgL0xlbmd0aCA2OCA+PgpzdHJlYW0KQlQKL0YxIDEyIFRmCjEwIDQwIFRkCigpIFRqCkVUCmVuZHN0cmVhbQplbmRvYmoKNSAwIG9iago8PCAvVHlwZSAvRm9udAogICAvU3VidHlwZSAvVHlwZTEKICAgL0Jhc2VGb250IC9IZWx2ZXRpY2EKICAgL0VuY29kaW5nIC9XaW5BbnNpRW5jb2RpbmcKPj4KZW5kb2JqCnhyZWYKMCA2CjAwMDAwMDAwMDAgNjU1MzUgZgowMDAwMDAwMDEwIDAwMDAwIG4KMDAwMDAwMDA2OCAwMDAwMCBuCjAwMDAwMDAxMjMgMDAwMDAgbgowMDAwMDAwMjUxIDAwMDAwIG4KMDAwMDAwMDM1MCAwMDAwMCBuCnRyYWlsZXIKPDwgL1NpemUgNiAvUm9vdCAxIDAgUiA+PgpzdGFydHhyZWYKNDE5CiUlRU9G',
            pdfmeVersion: '5.4.1',
        }
    }

    public getTemplate(): Template {
        return this.template
    }
}
