import { Template } from '@pdfme/common'

export class PernambucanasDynamicInsoleTemplate {
    private template: Template

    constructor() {
        this.template = {
            schemas: [
                [
                    {
                        name: 'CNPJ1',
                        type: 'text',
                        content: 'CNPJ',
                        position: { x: 3.3, y: 1 },
                        width: 6.09,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8.5,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'CNPJN1',
                        type: 'multiVariableText',
                        content: '{"CNPJN1":"CNPJN1"}',
                        position: { x: 9.3, y: 1 },
                        width: 25,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8.5,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{CNPJN1}',
                        variables: ['CNPJN1'],
                        required: false,
                    },
                    {
                        name: 'NOME1',
                        type: 'multiVariableText',
                        content: '{"NOME1":"NOME1"}',
                        position: { x: 3.7, y: 5 },
                        width: 40,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 7,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{NOME1}',
                        variables: ['NOME1'],
                        required: false,
                    },
                    // {
                    //     name: 'IND1',
                    //     type: 'text',
                    //     content: 'IND',
                    //     position: { x: 11.7, y: 5 },
                    //     width: 20,
                    //     height: 2,
                    //     rotate: 0,
                    //     alignment: 'left',
                    //     verticalAlignment: 'top',
                    //     fontSize: 7,
                    //     lineHeight: 1,
                    //     characterSpacing: 0,
                    //     fontColor: '#000000',
                    //     fontName: 'Oswald',
                    //     backgroundColor: '',
                    //     opacity: 1,
                    //     strikethrough: false,
                    //     underline: false,
                    //     required: false,
                    //     readOnly: false,
                    // },
                    {
                        name: 'MODELO_COR1',
                        type: 'multiVariableText',
                        content: '{"MODELO_COR1":"MODELO_COR1"}',
                        position: { x: 7.5, y: 8 },
                        width: 25,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 10.5,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: true,
                        readOnly: false,
                        text: '{MODELO_COR1}',
                        variables: ['MODELO_COR1'],
                        required: false,
                    },
                    {
                        name: 'ART1',
                        type: 'text',
                        content: 'ART1',
                        position: { x: 7.3, y: 13 },
                        width: 20,
                        height: 2.12,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8.5,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'ARTIGO1',
                        type: 'multiVariableText',
                        content: '{"ARTIGO1":"ARTIGO1"}',
                        position: { x: 17.3, y: 13 },
                        width: 12,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8.5,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{ARTIGO1}',
                        variables: ['ARTIGO1'],
                        required: false,
                    },
                    {
                        name: 'IBR1',
                        type: 'text',
                        content: 'IBR',
                        position: { x: 6.3, y: 17 },
                        width: 25,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 7,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'CNPJ2',
                        type: 'text',
                        content: 'CNPJ2',
                        position: { x: 38.4, y: 1 },
                        width: 7.14,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8.5,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'CNPJN2',
                        type: 'multiVariableText',
                        content: '{"CNPJN2":"CNPJN2"}',
                        position: { x: 44.4, y: 1 },
                        width: 25,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8.5,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{CNPJN2}',
                        variables: ['CNPJN2'],
                        required: false,
                    },
                    {
                        name: 'NOME2',
                        type: 'multiVariableText',
                        content: '{"NOME2":"NOME2"}',
                        position: { x: 38.8, y: 5 },
                        width: 40,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 7,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{NOME2}',
                        variables: ['NOME2'],
                        required: false,
                    },
                    // {
                    //     name: 'IND2',
                    //     type: 'text',
                    //     content: 'IND2',
                    //     position: { x: 46.8, y: 5 },
                    //     width: 20,
                    //     height: 2,
                    //     rotate: 0,
                    //     alignment: 'left',
                    //     verticalAlignment: 'top',
                    //     fontSize: 7,
                    //     lineHeight: 1,
                    //     characterSpacing: 0,
                    //     fontColor: '#000000',
                    //     fontName: 'Oswald',
                    //     backgroundColor: '',
                    //     opacity: 1,
                    //     strikethrough: false,
                    //     underline: false,
                    //     required: false,
                    //     readOnly: false,
                    // },
                    {
                        name: 'MODELO_COR2',
                        type: 'multiVariableText',
                        content: '{"MODELO_COR2":"MODELO_COR2"}',
                        position: { x: 42.6, y: 8 },
                        width: 25,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 10.5,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: true,
                        readOnly: false,
                        text: '{MODELO_COR2}',
                        variables: ['MODELO_COR2'],
                        required: false,
                    },
                    {
                        name: 'ART2',
                        type: 'text',
                        content: 'ART2',
                        position: { x: 42.4, y: 13 },
                        width: 20,
                        height: 2.12,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8.5,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'ARTIGO2',
                        type: 'multiVariableText',
                        content: '{"ARTIGO2":"ARTIGO2"}',
                        position: { x: 52.4, y: 13 },
                        width: 12,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8.5,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{ARTIGO2}',
                        variables: ['ARTIGO2'],
                        required: false,
                    },
                    {
                        name: 'IBR2',
                        type: 'text',
                        content: 'IBR2',
                        position: { x: 41.5, y: 17 },
                        width: 25,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 7,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'CNPJ3',
                        type: 'text',
                        content: 'CNPJ3',
                        position: { x: 73.4, y: 1 },
                        width: 7,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8.5,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'CNPJN3',
                        type: 'multiVariableText',
                        content: '{"CNPJN3":"CNPJN3"}',
                        position: { x: 79.4, y: 1 },
                        width: 25,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8.5,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{CNPJN3}',
                        variables: ['CNPJN3'],
                        required: false,
                    },
                    {
                        name: 'NOME3',
                        type: 'multiVariableText',
                        position: { x: 73.8, y: 5 },
                        required: false,
                        content: '{"NOME3":"NOME3"}',
                        width: 40,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 7,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{NOME3}',
                        variables: ['NOME3'],
                    },
                    // {
                    //     name: 'IND3',
                    //     type: 'text',
                    //     content: 'IND3',
                    //     position: { x: 81.8, y: 5 },
                    //     width: 20,
                    //     height: 2.12,
                    //     rotate: 0,
                    //     alignment: 'left',
                    //     verticalAlignment: 'top',
                    //     fontSize: 7,
                    //     lineHeight: 1,
                    //     characterSpacing: 0,
                    //     fontColor: '#000000',
                    //     fontName: 'Oswald',
                    //     backgroundColor: '',
                    //     opacity: 1,
                    //     strikethrough: false,
                    //     underline: false,
                    //     required: false,
                    //     readOnly: false,
                    // },
                    {
                        name: 'MODELO_COR3',
                        type: 'multiVariableText',
                        content: '{"MODELO_COR3":"MODELO_COR3"}',
                        position: { x: 77.6, y: 8 },
                        width: 25,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 10.5,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: true,
                        readOnly: false,
                        text: '{MODELO_COR3}',
                        variables: ['MODELO_COR3'],
                        required: false,
                    },
                    {
                        name: 'ART3',
                        type: 'text',
                        content: 'ART3',
                        position: { x: 77.4, y: 13 },
                        width: 20,
                        height: 2.12,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8.5,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'ARTIGO3',
                        type: 'multiVariableText',
                        content: '{"ARTIGO3":"ARTIGO3"}',
                        position: { x: 87.4, y: 13 },
                        width: 12,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8.5,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{ARTIGO3}',
                        variables: ['ARTIGO3'],
                        required: false,
                    },
                    {
                        name: 'IBR3',
                        type: 'text',
                        content: 'IBR3',
                        position: { x: 76.4, y: 17 },
                        width: 25,
                        height: 2,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 7,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Oswald',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                ],
            ],
            basePdf:
                'data:application/pdf;base64,JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUl0gL0NvdW50IDEgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCAyOTQuODAzIDU5LjUyOF0gL0NvbnRlbnRzIDQgMCBSIC9SZXNvdXJjZXMgPDwgPj4gPj4KZW5kb2JqCjQgMCBvYmoKPDwgL0xlbmd0aCAwID4+CnN0cmVhbQplbmRzdHJlYW0KZW5kb2JqCnhyZWYKMCA1CjAwMDAwMDAwMDAgNjU1MzUgZgowMDAwMDAwMDEwIDAwMDAwIG4KMDAwMDAwMDA2OCAwMDAwMCBuCjAwMDAwMDAxMjMgMDAwMDAgbgowMDAwMDAwMjQ2IDAwMDAwIG4KdHJhaWxlcgo8PCAvU2l6ZSA1IC9Sb290IDEgMCBSID4+CnN0YXJ0eHJlZgoyNzgKJSVFT0Y=',
            pdfmeVersion: '5.3.17',
        }
    }

    public getTemplate(): Template {
        return this.template
    }
}
