/*
  Warnings:

  - You are about to drop the `Tags` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `User` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE "Tags";

-- DropTable
DROP TABLE "User";

-- CreateTable
CREATE TABLE "ETIQUETAS" (
    "id" TEXT NOT NULL DEFAULT 'autogenerated',
    "loja" TEXT,
    "TipoEtiqueta" TEXT,
    "QTD" TEXT,
    "N_PEDIDO" TEXT,
    "CODIGO_MASTER" TEXT,
    "CODIGO_DIGITO" TEXT,
    "FORNECEDOR" TEXT,
    "COR" TEXT,
    "DESCRICAO" TEXT,
    "UC" TEXT,
    "GRADE" TEXT,
    "GRADE_QTD" TEXT,
    "TOTAL" TEXT,
    "SEMANA" TEXT,
    "NOME_EMPRESA" TEXT,
    "VOLUME" TEXT,
    "ANO" TEXT,
    "PROMOCAO" TEXT,
    "DEPARTAMENTO" TEXT,
    "N_TAMANHO" TEXT,
    "EAN" TEXT,
    "CODIGO_MATERIAL_SKU" TEXT,
    "PRECO_VDA" TEXT,
    "FAIXA" TEXT,
    "ITEM" TEXT,
    "SUBSEGMENTO" TEXT,
    "CICLOVIDA" TEXT,
    "EMPRESA_ID" INTEGER NOT NULL,

    CONSTRAINT "ETIQUETAS_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Empresa" (
    "ID" INTEGER NOT NULL,
    "NOME" TEXT NOT NULL,
    "APELIDO" TEXT NOT NULL,

    CONSTRAINT "Empresa_pkey" PRIMARY KEY ("ID")
);

-- AddForeignKey
ALTER TABLE "ETIQUETAS" ADD CONSTRAINT "ETIQUETAS_EMPRESA_ID_fkey" FOREIGN KEY ("EMPRESA_ID") REFERENCES "Empresa"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
