import { Template } from '@pdfme/common'

export class CaeduVolumeTemplate {
    private template: Template

    constructor() {
        this.template = {
            schemas: [
                [
                    {
                        name: 'RECTANGULE1',
                        type: 'rectangle',
                        position: { x: 3, y: 2 },
                        width: 68,
                        height: 36,
                        rotate: 0,
                        opacity: 1,
                        borderWidth: 0.3,
                        borderColor: '#000000',
                        color: '',
                        readOnly: true,
                        radius: 0,
                        required: false,
                        content: '',
                    },
                    {
                        name: 'RECTANGULE2',
                        type: 'rectangle',
                        position: { x: 3, y: 6 },
                        width: 68,
                        height: 6.1,
                        rotate: 0,
                        opacity: 1,
                        borderWidth: 0.3,
                        borderColor: '#000000',
                        color: '',
                        readOnly: true,
                        radius: 0,
                        required: false,
                        content: '',
                    },
                    {
                        name: 'RECTANGULE3',
                        type: 'rectangle',
                        position: { x: 16.1, y: 2 },
                        width: 25,
                        height: 4.3,
                        rotate: 0,
                        opacity: 1,
                        borderWidth: 0.3,
                        borderColor: '#000000',
                        color: '',
                        readOnly: true,
                        radius: 0,
                        required: false,
                        content: '',
                    },
                    {
                        name: 'RECTANGULE4',
                        type: 'rectangle',
                        position: { x: 40.8, y: 2 },
                        width: 7,
                        height: 4.3,
                        rotate: 0,
                        opacity: 1,
                        borderWidth: 0.3,
                        borderColor: '#000000',
                        color: '',
                        readOnly: true,
                        radius: 0,
                        required: false,
                        content: '',
                    },
                    {
                        name: 'RECTANGULE5',
                        type: 'rectangle',
                        position: { x: 3, y: 11.9 },
                        width: 68,
                        height: 7,
                        rotate: 0,
                        opacity: 1,
                        borderWidth: 0.3,
                        borderColor: '#000000',
                        color: '',
                        readOnly: true,
                        radius: 0,
                        required: false,
                        content: '',
                    },
                    {
                        name: 'RECTANGULE6',
                        type: 'rectangle',
                        position: { x: 18, y: 11.9 },
                        width: 53,
                        height: 14,
                        rotate: 0,
                        opacity: 1,
                        borderWidth: 0.3,
                        borderColor: '#000000',
                        color: '',
                        readOnly: true,
                        radius: 0,
                        required: false,
                        content: '',
                    },
                    {
                        name: 'QRCODE',
                        type: 'qrcode',
                        content: 'https://pdfme.com/',
                        position: { x: 75, y: 2 },
                        backgroundColor: '#ffffff',
                        barColor: '#000000',
                        width: 18,
                        height: 18,
                        rotate: 0,
                        opacity: 1,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'Pedido',
                        type: 'text',
                        content: 'Pedido',
                        position: { x: 4, y: 2.4 },
                        width: 12.44,
                        height: 3.44,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'tahoma',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'N_PEDIDO',
                        type: 'multiVariableText',
                        content: '{"N_PEDIDO":"N_PEDIDO"}',
                        position: { x: 16.66, y: 2.4 },
                        width: 24.34,
                        height: 3.7,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'tahoma',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{N_PEDIDO}',
                        variables: ['N_PEDIDO'],
                        required: false,
                    },
                    {
                        name: 'NF',
                        type: 'text',
                        content: 'NF',
                        position: { x: 42.07, y: 2.4 },
                        width: 6.35,
                        height: 3.17,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'tahoma',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'FORNECEDOR',
                        type: 'multiVariableText',
                        content: '{"FORNECEDOR":"FORNECEDOR"}',
                        position: { x: 4, y: 7 },
                        width: 65.62,
                        height: 5.56,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 10,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'tahoma',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{FORNECEDOR}',
                        variables: ['FORNECEDOR'],
                        required: false,
                    },
                    {
                        name: 'Produto',
                        type: 'text',
                        content: 'Produto',
                        position: { x: 4, y: 12 },
                        width: 14.29,
                        height: 6.88,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'middle',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'tahoma',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'GRADE',
                        type: 'multiVariableText',
                        content: '{"GRADE":"GRADE"}',
                        position: { x: 22, y: 12.57 },
                        width: 51.06,
                        height: 5.56,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'middle',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0.9,
                        fontColor: '#000000',
                        fontName: 'tahoma',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{GRADE}',
                        variables: ['GRADE'],
                        required: false,
                    },
                    {
                        name: 'COR',
                        type: 'multiVariableText',
                        content: '{"COR":"COR"}',
                        position: { x: 4, y: 18.91 },
                        width: 14.29,
                        height: 6.61,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'middle',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'tahoma',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{COR}',
                        variables: ['COR'],
                        required: false,
                    },
                    {
                        name: 'GRADE_QTD',
                        type: 'multiVariableText',
                        content: '{"GRADE_QTD":"GRADE_QTD"}',
                        position: { x: 22, y: 18.65 },
                        width: 50.01,
                        height: 7.14,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'middle',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'tahoma',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{GRADE_QTD}',
                        variables: ['GRADE_QTD'],
                        required: false,
                    },
                    {
                        name: 'CODIGO_MATERIAL1',
                        type: 'multiVariableText',
                        content: '{"CODIGO_MATERIAL1":"CODIGO_MATERIAL1"}',
                        position: { x: 4, y: 29.68 },
                        width: 28.31,
                        height: 3.44,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 9,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'tahoma',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{CODIGO_MATERIAL1}',
                        variables: ['CODIGO_MATERIAL1'],
                        required: false,
                    },
                    {
                        name: 'DESCRICAO',
                        type: 'multiVariableText',
                        content: '{"DESCRICAO":"DESCRICAO"}',
                        position: { x: 4, y: 33.47 },
                        width: 58.47,
                        height: 4.23,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'Arial_Bold',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{DESCRICAO}',
                        variables: ['DESCRICAO'],
                        required: false,
                    },
                    {
                        name: 'CF',
                        type: 'multiVariableText',
                        content: '{"CF":"CF"}',
                        position: { x: 72, y: 20 },
                        width: 8,
                        height: 6.61,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 25,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'tahoma',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{CF}',
                        variables: ['CF'],
                        required: false,
                    },
                    {
                        name: 'COD_MAT2',
                        type: 'multiVariableText',
                        content: '{"COD_MAT2":"COD_MAT2"}',
                        position: { x: 78, y: 22 },
                        width: 19.31,
                        height: 2.91,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'tahoma',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{COD_MAT2}',
                        variables: ['COD_MAT2'],
                        required: false,
                    },
                    {
                        name: 'N_P',
                        type: 'multiVariableText',
                        content: '{"N_P":"N_P"}',
                        position: { x: 78, y: 25 },
                        width: 19.05,
                        height: 3.44,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 8,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'tahoma',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{N_P}',
                        variables: ['N_P'],
                        required: false,
                    },
                    {
                        name: 'VolumeT',
                        type: 'text',
                        content: 'Volume',
                        position: { x: 77, y: 30.5 },
                        width: 24.34,
                        height: 3.97,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 10,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'tahoma',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        required: false,
                        readOnly: false,
                    },
                    {
                        name: 'VOLUME',
                        type: 'multiVariableText',
                        content: '{"VOLUME":"VOLUME"}',
                        position: { x: 75, y: 34.18 },
                        width: 24.34,
                        height: 5.82,
                        rotate: 0,
                        alignment: 'left',
                        verticalAlignment: 'top',
                        fontSize: 13,
                        lineHeight: 1,
                        characterSpacing: 0,
                        fontColor: '#000000',
                        fontName: 'tahoma',
                        backgroundColor: '',
                        opacity: 1,
                        strikethrough: false,
                        underline: false,
                        readOnly: false,
                        text: '{VOLUME}',
                        variables: ['VOLUME'],
                        required: false,
                    },
                ],
            ],
            basePdf:
                'data:application/pdf;base64,JVBERi0xLjQKMSAwIG9iago8PAovVHlwZSAvQ2F0YWxvZwovUGFnZXMgMiAwIFIKPj4KZW5kb2JqCjIgMCBvYmoKPDwKL1R5cGUgL1BhZ2VzCi9Db3VudCAxCi9LaWRzIFszIDAgUl0KPj4KZW5kb2JqCjMgMCBvYmoKPDwKL1R5cGUgL1BhZ2UKL1BhcmVudCAyIDAgUgovTWVkaWFCb3ggWzAgMCAyODMuNDY1IDExMy4zODZdCi9Db250ZW50cyA0IDAgUgovUmVzb3VyY2VzIDw8ID4+Cj4+CmVuZG9iago0IDAgb2JqCjw8Ci9MZW5ndGggOQo+PgpzdHJlYW0KZW5kc3RyZWFtCmVuZG9iagp4cmVmCjAgNQowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAwMTAgMDAwMDAgbiAKMDAwMDAwMDA2MCAwMDAwMCBuIAowMDAwMDAwMTE0IDAwMDAwIG4gCjAwMDAwMDAyNjcgMDAwMDAgbiAKdHJhaWxlcgo8PAovU2l6ZSA1Ci9Sb290IDEgMCBSCj4+CnN0YXJ0eHJlZgoyODgKJSVFT0Y=',
            pdfmeVersion: '5.5.1',
        }
    }

    public getTemplate(): Template {
        return this.template
    }
}
