-- CreateTable
CREATE TABLE "Tags" (
    "id" TEXT NOT NULL DEFAULT 'autogenerated',
    "QTD" TEXT,
    "N_PEDIDO" TEXT,
    "CODIGO_MASTER" TEXT,
    "CODIGO_DIGITO" TEXT,
    "FORNECEDOR" TEXT,
    "COR" TEXT,
    "DESCRICAO" TEXT,
    "UC" TEXT,
    "GRADE" TEXT,
    "GRADE_QTD" TEXT,
    "TOTAL" TEXT,
    "SEMANA" TEXT,
    "EMPRESA" TEXT,
    "VOLUME" TEXT,
    "ANO" TEXT,
    "PROMOCAO" TEXT,
    "DEPARTAMENTO" TEXT,

    CONSTRAINT "Tags_pkey" PRIMARY KEY ("id")
);
