-- AlterTable
ALTER TABLE "Tags" ADD COLUMN     "CICLOVENDA" TEXT,
ADD COLUMN     "CODIGO_MATERIAL_SKU" TEXT,
ADD COLUMN     "EAN" TEXT,
ADD COLUMN     "FAIXA" TEXT,
ADD COLUMN     "ITEM" TEXT,
ADD COLUMN     "N_TAMANHO" TEXT,
ADD COLUMN     "PRECO_VDA" TEXT,
ADD COLUMN     "SUBSEGMENTO" TEXT;
